### ISSUE TITLE
Merges pdf files

### ISSUE THREAD

**Issue by JohnnyMclain12** [ajaxray/merge2pdf#1]
Hello,

Can I marge 2 pdf files starting from the second page to the end, without type single page.

example : merge2pdf output.pdf input1.pdf input2.pdf~2-To the end

**Comment by ajaxray** [comment]
Hi @JohnnyMclain12 ,
Sorry, it's not supported so far.

But it seems to be a useful feature. So I am considering it as a feature request. 
Thanks a lot.

**Comment by ajaxray** [comment]
Hello @JohnnyMclain12 ,
Created a feature task based on this - #2
